# Generated by Django 5.0.3 on 2024-11-30 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homeapi", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Item",
            new_name="ItemsData",
        ),
    ]
